# Generated by Django 5.2.12 on 2026-03-10 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('guide', 'Poradnik'), ('instruction', 'Instrukcja'), ('standard', 'Standard'), ('template', 'Wzór'), ('checklist', 'Checklist'), ('lesson', 'Lessons Learned'), ('faq', 'FAQ'), ('onboarding', 'Onboarding')], max_length=32)),
                ('visibility', models.CharField(choices=[('internal', 'Internal'), ('project', 'Project'), ('private', 'Private')], default='internal', max_length=32)),
                ('is_pinned', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_articles', to=settings.AUTH_USER_MODEL)),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_articles', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
